### ISSUE TITLE
SOME ERRORS

### ISSUE THREAD

**Issue by mckChloe** [xuejianhuang/rummordetection_lstm#1]
大佬，你好
请问下遇到下面这个问题怎么解决呢？
Downloading: "https://github.com/lancopku/pkuseg-python/releases/download/v0.0.16/web.zip" to C:\Users\10150/.pkuseg\web.zip
Traceback (most recent call last):
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\urllib3\connection.py", line 426, in connect
    tls_in_tls=tls_in_tls,
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\urllib3\util\ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\10150\.conda\envs\pytorch\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\10150\.conda\envs\pytorch\lib\ssl.py", line 817, in __init__
    self.do_handshake()
  File "C:\Users\10150\.conda\envs\pytorch\lib\ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\10150\.conda\envs\pytorch\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:835: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 385, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/10150/PycharmProjects/rummordetection_lstm-main/train.py", line 72, in <module>
    train_dataloader = get_dataloader(model='train')
  File "C:\Users\10150\PycharmProjects\rummordetection_lstm-main\dataset.py", line 34, in get_dataloader
    dataset=RummorDataset(model=model)
  File "C:\Users\10150\PycharmProjects\rummordetection_lstm-main\dataset.py", line 13, in __init__
    self.contents=utils.key_to_index(self.contents,utils.word2vec,config.num_words)
  File "C:\Users\10150\PycharmProjects\rummordetection_lstm-main\utils.py", line 86, in key_to_index
    contents_S = pkuseg_cut(contents)
  File "C:\Users\10150\PycharmProjects\rummordetection_lstm-main\utils.py", line 43, in pkuseg_cut
    seg = pkuseg.pkuseg (model_name='web')  # 程序会自动下载所对应的细领域模型
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\pkuseg\__init__.py", line 207, in __init__
    download_model(config.model_urls[model_name], config.pkuseg_home, config.model_hash[model_name])
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\pkuseg\download.py", line 38, in download_model
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\pkuseg\download.py", line 44, in _download_url_to_file
    u = urlopen(url, stream=True, timeout=5)
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\10150\.conda\envs\pytorch\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=5)

**Comment by xuejianhuang** [comment]
这个是下载网络异常，如果你下载不了的话加我QQ:761780598,我单独把这个包发给你。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qiong ***@***.***&gt;; 
发送时间: 2021年12月17日(星期五) 晚上9:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [xuejianhuang/rummordetection_lstm] SOME ERRORS (Issue #1)





 
大佬，你好
 请问下遇到下面这个问题怎么解决呢？
 Downloading: "https://github.com/lancopku/pkuseg-python/releases/download/v0.0.16/web.zip" to C:\Users\10150/.pkuseg\web.zip
 Traceback (most recent call last):
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
 self.validate_conn(conn)
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 1010, in validate_conn
 conn.connect()
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\urllib3\connection.py", line 426, in connect
 tls_in_tls=tls_in_tls,
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\urllib3\util\ssl.py", line 450, in ssl_wrap_socket
 sock, context, tls_in_tls, server_hostname=server_hostname
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\urllib3\util\ssl.py", line 493, in _ssl_wrap_socket_impl
 return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
 File "C:\Users\10150.conda\envs\pytorch\lib\ssl.py", line 407, in wrap_socket
 _context=self, _session=session)
 File "C:\Users\10150.conda\envs\pytorch\lib\ssl.py", line 817, in init
 self.do_handshake()
 File "C:\Users\10150.conda\envs\pytorch\lib\ssl.py", line 1077, in do_handshake
 self._sslobj.do_handshake()
 File "C:\Users\10150.conda\envs\pytorch\lib\ssl.py", line 689, in do_handshake
 self._sslobj.do_handshake()
 socket.timeout: _ssl.c:835: The handshake operation timed out
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\requests\adapters.py", line 449, in send
 timeout=timeout
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\urllib3\util\retry.py", line 532, in increment
 raise six.reraise(type(error), error, _stacktrace)
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
 raise value
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
 chunked=chunked,
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 385, in _make_request
 self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 337, in _raise_timeout
 self, url, "Read timed out. (read timeout=%s)" % timeout_value
 urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=5)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "C:/Users/10150/PycharmProjects/rummordetection_lstm-main/train.py", line 72, in 
 train_dataloader = get_dataloader(model='train')
 File "C:\Users\10150\PycharmProjects\rummordetection_lstm-main\dataset.py", line 34, in get_dataloader
 dataset=RummorDataset(model=model)
 File "C:\Users\10150\PycharmProjects\rummordetection_lstm-main\dataset.py", line 13, in init
 self.contents=utils.key_to_index(self.contents,utils.word2vec,config.num_words)
 File "C:\Users\10150\PycharmProjects\rummordetection_lstm-main\utils.py", line 86, in key_to_index
 contents_S = pkuseg_cut(contents)
 File "C:\Users\10150\PycharmProjects\rummordetection_lstm-main\utils.py", line 43, in pkuseg_cut
 seg = pkuseg.pkuseg (model_name='web')  # 程序会自动下载所对应的细领域模型
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\pkuseg_init_.py", line 207, in init
 download_model(config.model_urls[model_name], config.pkuseg_home, config.model_hash[model_name])
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\pkuseg\download.py", line 38, in download_model
 _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\pkuseg\download.py", line 44, in _download_url_to_file
 u = urlopen(url, stream=True, timeout=5)
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\requests\api.py", line 75, in get
 return request('get', url, params=params, **kwargs)
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\requests\api.py", line 61, in request
 return session.request(method=method, url=url, **kwargs)
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\requests\sessions.py", line 542, in request
 resp = self.send(prep, **send_kwargs)
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\requests\sessions.py", line 655, in send
 r = adapter.send(request, **kwargs)
 File "C:\Users\10150.conda\envs\pytorch\lib\site-packages\requests\adapters.py", line 529, in send
 raise ReadTimeout(e, request=request)
 requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=5)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
